  OP(ADD      , "+"   , 10 , left+right      ,"+")
  OP(SUB      , "-"   , 11 , left-right      ,"-")
  OP(MUL      , "*"   , 12 , left*right      ,"*")
  OP(DIV      , "/"   , 13 , left/right      ,"/")
  OP(POW      , "^"   , 14 , pow(left, right),"^")
  OP(EQAL     , "=="  , 15 , left , "=="    )
  OP(MORE     , ">"   , 16 , left , "\\>"   )
  OP(LESS     , "<"   , 17 , left , "\\<"   )
  OP(MORE_E   , ">="  , 18 , left , "\\>="  )
  OP(LESS_E   , "<="  , 19 , left , "\\<="  )
  OP(N_EQAL   , "!="  , 20, left , "!="    )
  OP(ASSIGN   , "="   , 21, left , "="     )
