  OP(SIN   , "sin"  , 0 ,   sin(right)      ,"sin"  )
  OP(COS   , "cos"  , 1 ,   cos(right)      ,"cos"  )
  OP(SQRT  , "√"    , 2 ,   sqrt(right)     ,"√"    )
  OP(LN    , "ln"   , 3 ,    ln(right)      ,"log"  )
  OP(NOT   , "!"    , 4 ,   right           ,"!"    )
  OP(OUT   , "out"  , 5 ,   right           ,"out"  )
  OP(OUT_C , "out_c", 6 ,   right           ,"out_c")
  OP(IN    , "in"   , 7 ,   right           ,"in"   )
  OP(CALL  , "call" , 8 ,   right           ,"call" )
  OP(RET   , "ret"  , 9 ,   right           ,"ret"  )
